Sistema Control Soporte/Controllers/SoporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using System.Configuration;

namespace Sistema_Control_Soporte.Controllers
{
    public class SoporteController : Controller
    {
        // GET: Soporte
        public ActionResult Index(int tipo = 0)
        {
            if (Session.Count == 0)
            {
                Session["user"] = "";
                Session["pass"] = "";
            }
            if (Session["user"].Equals("") || Session["pass"].Equals("") || Session["user"] == null || Session["pass"] == null)
            {
                ViewBag.error = "Sesion vencida";
                return RedirectToAction("Login");
            }
            else
            {
                Datos_BD cnn = new Datos_BD();
                DataTable dt = null;
                if (tipo == 0)
                {
                    dt = cnn.Consultar_tickets_sin_respuesta();
                }
                if (tipo == 1)
                {
                    dt = cnn.Consultar_tickets_con_respuesta();
                }
                if (tipo == 2)
                {
                    dt = cnn.Consultar_tickets_todos();
                }
                if (tipo == 3)
                {
                    int idAgente = 0;

                    idAgente = int.Parse(cnn.Consultar_agente(Session["user"].ToString()).Rows[0]["id_agente"].ToString());
                    dt = cnn.Consultar_tickets_xagente(idAgente);
                }
                

                List<ticket> lista = new List<ticket>();

                foreach (DataRow r in dt.Rows)
                {
                    ticket t = new ticket();

                    t.id = r["idTicket"].ToString();
                    t.descripcion = r["descripcion"].ToString();
                    t.fechaRegistro = DateTime.Parse(r["fechaRegistro"].ToString());
                    t.horaRegistro = DateTime.Parse(r["horaRegistro"].ToString());
                    t.situacion = r["situacion"].ToString();
                    t.nombreCliente = cnn.Consultar_cliente(int.Parse(r["idCliente"].ToString())).Rows[0]["nombre"].ToString();
                    //falta hacer las consultas al departamento.
                    t.departamento = cnn.Consultar_deptoxticket(int.Parse(r["idTicket"].ToString())).Rows[0]["nombre"].ToString();
                    t.tema = cnn.Consultar_tema(int.Parse(r["idTema"].ToString())).Rows[0]["descripcion"].ToString();
                    t.fuente = cnn.Consultar_fuente(int.Parse(r["idFuente"].ToString())).Rows[0]["nombre"].ToString();

                    lista.Add(t);
                }
                ViewBag.tickets = lista;

                return View();
            }
        }

        // GET: Login
        public ActionResult Login()
        {
            Session["user"] = "";
            Session["pass"] = "";
            return View();
        }

        // GET: Login
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            Datos_BD cnn = new Datos_BD();

            if (cnn.validarUsuario(username, password))
            {
                Session["user"] = username;
                Session["pass"] = password;

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.error = "Usuario no valido";
                return View();
            }

        }
        // GET: Respuesta
        public ActionResult Respuesta(int idt)
        {
            if (Session.Count == 0)
            {
                Session["user"] = "";
                Session["pass"] = "";
            }
            if (Session["user"].Equals("") || Session["pass"].Equals("") || Session["user"] == null || Session["pass"] == null)
            {
                ViewBag.error = "Sesion vencida";
                return RedirectToAction("Login");
            }
            else
            {
                Datos_BD cnn = new Datos_BD();
                DataTable dt = cnn.Consultar_ticket(idt);

                ticket t = new ticket();

                t.id = idt.ToString();
                t.descripcion = dt.Rows[0]["descripcion"].ToString();
                t.fechaRegistro = DateTime.Parse(dt.Rows[0]["fechaRegistro"].ToString());
                t.horaRegistro = DateTime.Parse(dt.Rows[0]["horaRegistro"].ToString());
                t.situacion = dt.Rows[0]["situacion"].ToString();
                t.nombreCliente = cnn.Consultar_cliente(int.Parse(dt.Rows[0]["idCliente"].ToString())).Rows[0]["nombre"].ToString();

                t.departamento = cnn.Consultar_deptoxticket(int.Parse(dt.Rows[0]["idTicket"].ToString())).Rows[0]["nombre"].ToString();
                t.tema = cnn.Consultar_tema(int.Parse(dt.Rows[0]["idTema"].ToString())).Rows[0]["descripcion"].ToString();
                t.fuente = cnn.Consultar_fuente(int.Parse(dt.Rows[0]["idFuente"].ToString())).Rows[0]["nombre"].ToString();
                string rutaatt = ConfigurationManager.AppSettings["rutaAttach"];
                string rutaWeb = ConfigurationManager.AppSettings["rutaWeb"];
                List<string> listaa = new List<string>();
                if (Directory.Exists(rutaatt + dt.Rows[0]["idCliente"].ToString() + "\\" + dt.Rows[0]["idTicket"].ToString()))
                {
                    string[] archivos = Directory.GetFiles(rutaatt + dt.Rows[0]["idCliente"].ToString() + "\\" + dt.Rows[0]["idTicket"].ToString());

                    foreach (string f in archivos)
                    {
                        FileInfo fi = new FileInfo(f);
                        listaa.Add(rutaWeb + dt.Rows[0]["idCliente"].ToString() + "/" + dt.Rows[0]["idTicket"].ToString() + "/" + fi.Name);
                    }
                    t.Archivos = listaa;
                }

                ViewBag.ticket = t;

                DataTable dtrespuestas = cnn.Consultar_respuestas_x_ticket(idt);

                List<respuesta> respuestas = new List<respuesta>();

                foreach (DataRow r in dtrespuestas.Rows)
                {
                    respuesta tr = new respuesta();
                    tr.contenido = r["contenido"].ToString();
                    tr.id = idt.ToString();
                    tr.Estado = r["Estado"].ToString();
                    tr.Fecha = DateTime.Parse(r["Fecha_respuesta"].ToString());
                    tr.Hora = DateTime.Parse(r["Hora_respuesta"].ToString());
                    tr.contador = r["contador_respuesta"].ToString();
                    if (r["esCliente"].ToString().Equals("0"))
                    {
                        tr.escliente = false;
                        tr.Agente = cnn.Consultar_agentexid(int.Parse(r["id_agente"].ToString())).Rows[0]["nombre"].ToString() + " " + cnn.Consultar_agentexid(int.Parse(r["id_agente"].ToString())).Rows[0]["apellidos"].ToString();
                    }
                    else
                    {
                        tr.escliente = true;
                        tr.Agente = cnn.Consultar_cliente(int.Parse(r["id_agente"].ToString())).Rows[0]["nombre"].ToString();
                    }

                    if (Directory.Exists(rutaatt + dt.Rows[0]["idCliente"].ToString() + "\\" + dt.Rows[0]["idTicket"].ToString() + "\\" + tr.contador) )
                    {
                        string[] archivos = Directory.GetFiles(rutaatt + dt.Rows[0]["idCliente"].ToString() + "\\" + dt.Rows[0]["idTicket"].ToString() + "\\" + tr.contador);

                        foreach (string f in archivos)
                        {
                            FileInfo fi = new FileInfo(f);
                            t.Archivos.Add(rutaWeb + dt.Rows[0]["idCliente"].ToString() + "/" + dt.Rows[0]["idTicket"].ToString() + "/" + tr.contador +"/" + fi.Name);
                        }
                    }

                    respuestas.Add(tr);

                }

                ViewBag.repuestas = respuestas;
                return View();
            }
        }

        // GET: Solicitud
        public ActionResult Solicitud()
        {
            Datos_BD cnn = new Datos_BD();

            ViewBag.Message = "";
            DataTable dtdeptos = cnn.Consultar_departamentos();

            List<string> listad = new List<string>();
            foreach (DataRow r in dtdeptos.Rows)
            {
                listad.Add(r["nombre"].ToString());
            }

            ViewBag.listad = listad;

            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Solicitud(string Asunto, string Nombre, string Email, string departamento,  string descripcion, HttpPostedFileBase uploadFile)
        {
            ViewBag.Message = "";
              Datos_BD cnn = new Datos_BD();
            
            try
            {
                int idCliente = 0;
                DataTable cliente = cnn.Consultar_clientexmail(Email);
                if (cliente.Rows.Count == 0)
                {
                    cnn.Agregar_cliente(Nombre, Email, "0");

                }
                cliente = cnn.Consultar_clientexmail(Email);

                DataTable depts = cnn.Consultar_departamentos();
                int idd = 1;
                foreach (DataRow r in depts.Rows)
                {
                    if (r["nombre"].ToString().Equals(departamento))
                    {
                        idd = int.Parse(r["idDepartamento"].ToString());
                    }
                }
                
                DataTable resp = cnn.Agregar_ticket(descripcion, Asunto, int.Parse(cliente.Rows[0]["idCliente"].ToString()), 1, 2, idd);
                int id_ticket = int.Parse(resp.Rows[0][0].ToString());

                string rutaatt = ConfigurationManager.AppSettings["rutaAttach"];
                if (uploadFile != null && uploadFile.ContentLength > 0)
                    try
                    {

Sistema Control Soporte/Views/Soporte/Index.cshtml
@using Sistema_Control_Soporte.Controllers;
@{
    
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <div class="col">
            <table id="example" class="table table-bordered  display nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Ticket</th>
                        <th>Asunto</th>
                        <th>departamento</th>
                        <th>Cliente</th>
                        <th>Fecha</th>
                        <th>Fuente</th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                   @{ 
                       List<ticket> lista;
                       lista = ViewBag.tickets;

                       foreach (ticket t in lista)
                       {
                            <tr>
                                <td>@t.id</td>
                                <td>@t.situacion</td>
                                <td>@t.departamento</td>
                                <td>@t.nombreCliente</td>
                                <td>@t.fechaRegistro</td>
                                <td>@t.fuente</td>
                                <td>
                                    <div class="text-center">
                                        <div class="btn-group">

                                            <a class="btnrespuesta" href="@Url.Action("Respuesta", "Soporte", new { idt = t.id})" idt="@t.id">Responder</a>

                                        </div>



                                    </div>
                                </td>

                            </tr>
                       }

                   }

                </tbody>
            </table>
        </div>
    </div>
</div>

Sistema Control Soporte/Views/Soporte/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/64d58efce2.js"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/estilo.css" />

    <script src="https://cdn.tiny.cloud/1/dohckbplsb1w4y863a99x6emvl8xmx06ir6ai018yfl5b71b/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <title>Soporte Técnico</title>

    <script src="~/jquery/jquery-3.3.1.min.js"></script>

    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/alertify.js"></script>
    <script src="~/Scripts/alertify.min.js"></script>
</head>
<body>

    <div class="container">
        <div class="forms-container">
            <div class="signin-signup">
                <form action="Login" method="post" class="sign-in-form">
                    <h2 class="title">Inicio</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <input type="text" placeholder="Usuario" name="username" />
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <input type="password" placeholder="contraseña" name="password" />
                    </div>
                    <input type="submit" value="Entrar" class="btn solid" />


                </form>
                <form action="#" class="sign-up-form">
                    <h2 class="title">Registro</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <input type="text" placeholder="Usuario" />
                    </div>
                    <div class="input-field">
                        <i class="fas fa-envelope"></i>
                        <input type="email" placeholder="Email" />
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <input type="password" placeholder="contraseña" />
                    </div>
                    <input type="submit" class="btn" value="Registrar" />





                </form>
              
            </div>
        </div>

        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>¿Eres nuevo aqui?</h3>
                    <p>
                        Registrate para poder ingresar a nuestro sistema!
                    </p>
                    <button class="btn transparent" id="sign-up-btn">
                        Registrar
                    </button>
                </div>
                <div class="content">
                    <h3>¿Quieres agregar un caso?</h3>
                    <p>
                        Agregalo aquí directamente!
                    </p>
                    <a class="btn transparent" href="@Url.Action("Solicitud", "Soporte")" style="padding: 3% 3% 3% 3%; " >
                        Crear Caso
                    </a>
                </div>
                <img src="~/img/img1.svg" class="image" alt="" />
            </div>
            <div class="panel right-panel">
                <div class="content">
                    <h3>¿Como ingresar ?</h3>
                    <p>
                        Completa los siguientes campos para poder registrarte de manera correcta.
                    </p>
                    <button class="btn transparent" id="sign-in-btn">
                        Inicio
                    </button>
                </div>
                <img src="~/img/img2.svg" class="image" alt="" />
            </div>
        </div>
    </div>


  



        @{
            String res = "";
            res = ViewBag.error;
            if (res != "")
            {
                <script>
                    alertify.error("Error:  @res");
                </script>
            }

        }
        <script src="~/app.js"></script>
</body>
</html>

Sistema Control Soporte/Views/Soporte/Respuesta.cshtml
@using Sistema_Control_Soporte.Controllers;
@{
    ViewBag.Title = "Respuesta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdn.tiny.cloud/1/dohckbplsb1w4y863a99x6emvl8xmx06ir6ai018yfl5b71b/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#mytextarea',
        menubar: false,
        statusbar: false,
        setup: function (ed) {
            ed.on("change", function (e) {
                if (tinymce.activeEditor.getContent() != "") {
                    $("#btnenviar").css("visibility", "visible");
                } else {
                    $("#btnenviar").css("visibility", "hidden");
                        ;
                }
            });
           
        }
    });
</script>
<h2>Respuesta</h2>
<script src="~/jquery/jquery-3.4.1.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>

<div class="card-group">
    <div class="col-lg-12">
        <div class="card-header" style="height: 120px;">
            @{
                ticket t = ViewBag.ticket;

            }
            <div style="width: 50%; float:left;">ID Ticket : @t.id  </div>
            <div style="width: 50%; float:left;">Fecha Registro : @t.fechaRegistro  </div>
            <div style="width: 50%; float:left;">Cliente : @t.nombreCliente</div>
            <div style="width: 50%; float:left;">Asunto : @t.situacion    </div>
            <div style="width: 50%; float:left;">Departamento : @t.departamento  </div>
            <div style="width: 50%; float:left;">Tema : @t.tema  </div>
            <div style="width: 50%; float:left;">Fuente : @t.fuente  </div>

        </div>
    </div>
    <div class="col-lg-12">
        <div class="card-body">
            <div class="card-group" style="border: solid 1px black;">
                <div class="card-header">
                    @t.nombreCliente  @t.horaRegistro
                </div>
                <div class="card-body">
                    @Html.Raw(HttpUtility.HtmlDecode(t.descripcion))
                </div>
                @{
                    if (t.Archivos != null)
                    {
                        if (t.Archivos.Count > 0)
                        {
                        <div class="card-body">

                            @foreach (string f in t.Archivos)
                            {
                                <a href="@f"> Adjunto  </a>
                            }
                        </div>


                            }
                        }
                    }
            </div>
        </div>
        @{
            List<respuesta> lista = new List<respuesta>();
            lista = ViewBag.repuestas;
            if (lista.Count > 0)
            {
                foreach (respuesta re in lista)
                {

                    <div class="card-body">

                        <span class="pull-right avatar" style="float: left; width: 9%; margin-bottom: 1%;">
                            <img class="avatar" alt="Avatar" src="//www.gravatar.com/avatar/253db121e1511b51d1cd2cf7308b8b7b?s=80&amp;d=mm">
                        </span>

                        <div class="card-group" style="border: solid 1px black; float: right ;width: 90%;margin-bottom: 1%; ">
                            <div class="card-header">
                                @re.Agente  @re.Fecha @re.contador
                            </div>
                            <div class="card-body">
                                @Html.Raw(HttpUtility.HtmlDecode(re.contenido))
                            </div>
                            @{
                                if(re.Archivos != null) { 
                                    if (re.Archivos.Count > 0)
                                    {
                                        <div class="card-body">

                                            @foreach (string f in re.Archivos)
                                            {
                                                <a href="@f">  Adjunto </a>
                                            }
                                        </div>


                                    }
                                }
                            }
                        </div>

                    </div>
                    <br />
                                    }
                                }

        }
    </div>
    <div class="col-lg-12">
        @using (Html.BeginForm("Respuesta", "Soporte", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <textarea id="mytextarea" name="descripcion"></textarea>
            <input type="hidden" value="@t.id" name="id_ticket"></input>
            <br />
            <button id="btnenviar" class="btn btn-primary" type="submit" style="visibility:hidden;">Enviar Respuesta al Cliente</button>
        }

        @using (Html.BeginForm("Finalizar", "Soporte", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <input type="hidden" value="@t.id" name="id_ticket"></input>

            <button class="btn btn-primary" type="submit">Cerrar Caso</button>
        }

    </div>

</div>
<script>
    function myCustomOnChangeHandler(inst) {
        alert("Some one modified something");
        alert("The HTML is now:" + inst.getBody().innerHTML);
    }

</script>

Sistema Control Soporte/Views/Soporte/Solicitud.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Solicitud</title>
    <script src="https://cdn.tiny.cloud/1/dohckbplsb1w4y863a99x6emvl8xmx06ir6ai018yfl5b71b/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/tablas.css">
    <link rel="stylesheet" href="~/fonts.css">
    <link rel="stylesheet" href="~/Content/alertifyjs/alertify.css" />
    <script>
        tinymce.init({
            selector: '#mytextarea',
            statusbar: false,
            menubar: false
        });
    </script>

    <script src="~/jquery/jquery-3.3.1.min.js"></script>

    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/alertify.js"></script>
    <script src="~/Scripts/alertify.min.js"></script>
</head>
<body>
    <header>
        <nav>

            <ul>
                <img class="imagen" src="~/img/logo.jpg">





                <li><a href="#"><span class="quinto"><i class="icon icon-database"></i></span>Base de conocimiento</a></li>
                <li><a href="@Url.Action("Login", "Soporte")"><span class="quinto"><i class="icon icon-exit"></i></span>Iniciar Sesion Agente</a></li>
            </ul>
        </nav>
    </header>

    @{
        if (ViewBag.Message != "")
        {
            string mensaje = ViewBag.Message;

            if (mensaje.ToLower().Contains("error"))
            {
                <script>
                alertify.error('@mensaje');
                </script>
            }
            else
            {
                <script>
                alertify.success('@mensaje');
                </script>
            }


        }
    }

    <div class="container-fluid">
        <div class="row">
            <div class="container">
                <div class="container">
                    <div class="row mt-3">
                        <div class="col">
                            @using (Html.BeginForm("Solicitud", "Soporte", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <div class="form-group">
                                    <label for="pass">Asunto</label>
                                    <input type="text" class="form-control" placeholder="Asunto" name="asunto" id="actualizacion">

                                </div>

                                <div class="form-group">
                                    <label for="pass">Nombre</label>
                                    <input type="text" class="form-control" placeholder="Nombre" name="nombre" id="actualizacion">

                                </div>

                                <div class="form-group">
                                    <label for="mensaje">Correo Electrónico</label>
                                    <input type="email" class="form-control" placeholder="Email" name="email" id="email">

                                </div>



                                <div class="form-group">
                                    <label for="Asignado">Departamento</label>
                                    <select name="departamento" id="depto" class="form-control">
                                        <option selected>Seleccione un departamento</option>
                                        @{
                                            List<string> lista = ViewBag.listad;

                                            foreach (string depto in lista)
                                            {
                                                <option>@depto</option>
                                            }
                                        }
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="pass">Descipción</label>
                                    <textarea id="mytextarea" name="descripcion"></textarea>

                                </div>
                                <div class="form-group">

                                    <input type="file" id="file" name="uploadFile" /><br><br>

                                </div>


                                <div class="col-12 col-sm-9 col-md-4">
                                    <button class="btn btn-primary btn-block" type="submit" onclick="">Enviar</button>
                                </div>
                            }
                        </div>
                    </div>




                </div>
            </div>
        </div>

</body>
</html>